# Generated by Django 5.2.7 on 2025-12-05 15:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_timersession'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('event_date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('category', models.CharField(choices=[('Work', 'Work'), ('Personal', 'Personal'), ('School', 'School'), ('Meeting', 'Meeting'), ('Other', 'Other')], default='Other', max_length=20)),
                ('color', models.CharField(choices=[('#1f6feb', 'Blue'), ('#22c55e', 'Green'), ('#f59e0b', 'Orange'), ('#ef4444', 'Red'), ('#8b5cf6', 'Purple'), ('#ec4899', 'Pink')], default='#1f6feb', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['event_date', 'start_time'],
            },
        ),
    ]
