# Generated by Django 5.2.7 on 2025-12-10 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_userstreak'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='add_to_calendar',
            field=models.BooleanField(default=False, help_text='Automatically sync this task to calendar'),
        ),
        migrations.AddField(
            model_name='task',
            name='linked_calendar_event',
            field=models.ForeignKey(blank=True, help_text='Calendar event linked to this task', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_task', to='main.calendarevent'),
        ),
    ]
