# Generated by Django 5.2.7 on 2025-12-10 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_task_add_to_calendar_task_linked_calendar_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='is_recurring',
            field=models.BooleanField(default=False, help_text='Is this a recurring event?'),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='parent_event',
            field=models.ForeignKey(blank=True, help_text='The original event this instance belongs to (for recurring events)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recurring_instances', to='main.calendarevent'),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='recurrence_end_date',
            field=models.DateField(blank=True, help_text='When to stop creating recurring instances', null=True),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='recurrence_pattern',
            field=models.CharField(blank=True, choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], help_text='How often this event repeats', max_length=20, null=True),
        ),
    ]
