# Generated by Django 5.2.7 on 2025-12-10 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_calendarevent_is_recurring_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='reminder_enabled',
            field=models.BooleanField(default=False, help_text='Enable reminder notification for this event'),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='reminder_minutes_before',
            field=models.IntegerField(default=15, help_text='Minutes before event to show reminder (15, 30, 60, 1440 for 1 day)'),
        ),
    ]
