# Generated by Django 5.2.7 on 2025-12-11 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_subtask'),
        ('main', '0009_calendarevent_reminder_enabled_and_more'),
    ]

    operations = [
    ]
